### ISSUE TITLE
The jewelry table ticking loop advancement trick doesn't seem to function in 1.17 anymore.

### ISSUE THREAD

**Issue by CreeperMagnet** [CreeperMagnet/tcc#38]
WE NEED A NEW GIMMICK!!! AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

`inventory_changed` no longer triggers when you exit a GUI.

We can't use this to check if the jewelry table is open to reduce lag. Life is pain. Pure, undiluted pain.

**Comment by CreeperMagnet** [comment]
Check if mojang fixes this one when the next snapshot comes out. There's a possibility that it's fixed, there's a possibility that it isn't.

**Comment by MASTRIO** [comment]
never fear for I have a solution!

just explode

**Comment by CreeperMagnet** [comment]
Haha! Hilarious! I’m laughing! Pure comedy!

Take it out of my github, thanks. If you can’t actually help or contribute anything, don’t comment.

**Comment by CreeperMagnet** [comment]
> Check if mojang fixes this one when the next snapshot comes out. There's a possibility that it's fixed, there's a possibility that it isn't.

Turns out that Mojang fixed this behavior by making it work properly—giving players items now triggers *after* the GUI is open, so it wouldn't classify as an inventory change.

However, the existing behavior of `inventory_changed` works most of the time, as if you take any item out of the jewelry table or put any into the jewelry table (or, in fact, change your inventory in any way), the jewelry table should stop ticking properly.

The only edge case is when you click the table then immediately exit without doing anything. The only way to stop the jewelry table from ticking in that case would be to change your inventory while outside the table... which is a rather common occurrence, so I'm marking this as won't fix.

**Comment by CreeperMagnet** [comment]
Mojang broke our workaround. Reopening.

I crave the sweet release of death.

**Comment by CreeperMagnet** [comment]
Fixed in V0.5 beta 6... by making it somewhat laggier and based on distance. :(
